version: '3.8'

services:
  web:
    image: ghcr.io/smpcat/gestoreventos:latest
    container_name: gestoreventos
    user: "root"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /share/CACHEDEV1_DATA/Container/gestoreventos/data:/app/data
      - /share/CACHEDEV1_DATA/Container/gestoreventos/public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/prod.db
      - NEXT_PUBLIC_BASE_URL=https://eventos-smp.duckdns.org
      - JWT_SECRET=cambia_esta_clave_por_una_super_segura_para_el_nas
    networks:
      - proxy_network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_RUN_FIRST=true
    command: gestoreventos

networks:
  proxy_network:
    external: true
