version: '3.8'

services:
  gestor-eventos:
    image: ghcr.io/smpcat/gestoreventos:latest
    container_name: gestoreventos_prod
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/prod.db
      - NEXT_PUBLIC_BASE_URL=https://eventos-smp.duckdns.org
      - JWT_SECRET=cambia_esta_clave_por_una_super_segura_para_el_nas
    # Redirigimos el contenedor a la red del proxy maestro
    networks:
      - proxy_network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower_gestoreventos
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mapeamos el archivo de autenticación de Docker del NAS para acceder a GHCR
      - /share/CACHEDEV1_DATA/.qpkg/container-station/homes/admin/.docker/config.json:/config.json:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300 # Comprueba cada 5 minutos
      - WATCHTOWER_INCLUDE_STOPPED=false
    # Argumento posicional: Solo vigila ESTE contenedor, ignora el resto del NAS
    command: gestoreventos_prod

# --------------------------------------------------------
# CONEXIÓN A RED EXTERNA (Core-Proxy)
# --------------------------------------------------------
networks:
  proxy_network:
    external: true
